### ISSUE TITLE
Creating torrent -- file order NOT preserved

### ISSUE THREAD

**Issue by Oifan** [Novik/ruTorrent#1001]
Hi,
I just found out that whenever creating new torrent that contains several files (no sub-folder), the order in the resulting torrent is not preserved - I have also made a fix for it, now it works:
```diff
--- rutorrent/php/Torrent.php	Wed Oct 16 12:40:32 2013
+++ rutorrent_/php/Torrent.php	Tue Jan 27 21:01:52 2015
@@ -456,7 +456,7 @@
 		if(!$this->basedir)
         		$files  = array_map( 'realpath', $files );
 		sort( $files );
-		usort( $files, create_function( '$a,$b', 'return strrpos($a,DIRECTORY_SEPARATOR)-strrpos($b,DIRECTORY_SEPARATOR);' ) );
+		uasort( $files, create_function( '$a,$b', 'return strrpos($a,DIRECTORY_SEPARATOR)-strrpos($b,DIRECTORY_SEPARATOR);' ) );
 
 		if($this->basedir)
 			$path   = explode( DIRECTORY_SEPARATOR, $this->basedir );
@@ -466,8 +466,9 @@
 	        $length = $piece_length;
         	$piece  = $pieces = '';
 	        $info_files = array();
-		foreach( $files as $i => $file )
+		for( $i = 0; $i < count($files); ++$i )
 		{
+			$file = $files[$i];
 			$this->notify_log( 'Hash '.$file );
 			if( $path != array_intersect_assoc( $file_path = explode( DIRECTORY_SEPARATOR, $file ), $path ) ) 
 			{
```

**Comment by Novik** [comment]
1) IMHO your code will not work by the normal way.
2) Please, give me link to the specifications, when you obtain an idea about required order of files.

**Comment by Oifan** [comment]
* @Novik: AD 1: My code works, I am using it right now on my Raspberry Pi - file order is preserved now - I have ArchLinux (kernel 3.18.3-1) + PHP 5.6.5-1 + webserver lighttpd 1.4.35-1;
* @Novik: AD 2: The order I expect is the same as order used by uTorrent - sort everything alphabetically, but folders have higher priority than files (so correct order would be: a/a, a/b, b/a, b/b, a, b). So I have created a torrent from 1 folder containing several files (in my case I had 26 MKV files each having the same file-name prefix + different 2-digit number 01...26) -- but the order within the torrent file was not alphabetical (it was 18, 19, 17, 16, 15, 20, 21, 25). Just think/test what `foreach( $files as $i => $file )` does -- I have checked it on my Raspberry Pi and I have found out that it the iteration does **not** go for `$i` from 0 **sequentially**, but rather randomly -- so the order created by `usort` or `uasort` function is not preserved.

**Comment by Oifan** [comment]
@Novik: And what do you mean by this line? :
> your code will not work by the normal way

The changes are very trivial:
* I have only replaced `usort` with `uasort` (because the latter one does not change the order of items that are equal in this sort [but weren't in the previous one]),
* and I have just replaced the way of iterating the array `$files` - so I don't use some random default order of `foreach` command (which is similar to iterating through HashMap in Java), but rather sequential order using `$i` that starts at `0` and ends just before `count($files)`.

**Comment by Novik** [comment]
> The order I expect is the same as order used by uTorrent - sort everything alphabetically

Your code will not sort everything alphabetically. Try to think about one question: what will happens, if filenames will contain non-ASCII, UTF-8 chars?

**Comment by Novik** [comment]
And about foreach - try to read this: http://stackoverflow.com/questions/4733188/is-foreach-guaranteed-to-iterate-in-the-array-order-in-php

**Comment by Novik** [comment]
About your code.
1. It may be rewritten in more compact form - 
```
sort( $files );

foreach ($files as $key => $value) {
    echo "Key: $key; Value: $value<br />\n";
}
```
Try to think - why.
2. It doesn't preserves dirs order. Try to check it (any version) with such input data:
$files = array("/a/b/05.avi", "/a(b)04.avi", "/azbz03.avi");
3. It doesn't preserves files order inside one dir. Because PHP5 is NOT unicode-aware. And function `sort` will work with a bytes instead charactes.

About existing code.
It guarantees only one thing: files with a more deep level will be processed after files with a less deep level. It doesn't preserves files order inside one dir. Because 1) standard doesn't require this 2) this is enough for my purposes.

**Comment by Oifan** [comment]
@Novik: Now I see your point - I have misunderstood the functionality of `uasort()` - in combination with `for` loop it has no meaning.
But some things I have written are still true - e.g. if you call `usort()` **after** `sort()` then the **order** created by `sort()` **will be destroyed**. If it wouldn't, your solution would work with no problems.
So if you still haven't fixed this issue, here is a patch (it will sort all files within each directory alphabetically, while directories have **higher** priority):
``` diff
--- rutorrent/php/Torrent.php	Wed Oct 16 12:40:32 2013
+++ rutorrent_/php/Torrent.php	Sat Mar 28 09:23:45 2015
@@ -455,8 +455,7 @@
 	{
 		if(!$this->basedir)
         		$files  = array_map( 'realpath', $files );
-		sort( $files );
-		usort( $files, create_function( '$a,$b', 'return strrpos($a,DIRECTORY_SEPARATOR)-strrpos($b,DIRECTORY_SEPARATOR);' ) );
+		usort( $files, create_function( '$a,$b', '$cmp=strrpos($b,DIRECTORY_SEPARATOR)-strrpos($a,DIRECTORY_SEPARATOR); return $cmp!=0 ? $cmp : strcmp($a,$b);' ) );
 
 		if($this->basedir)
 			$path   = explode( DIRECTORY_SEPARATOR, $this->basedir );
```

**Comment by Novik** [comment]
1) You are right, line with a sort in existing code do nothing. Really this is a line from original creator of this file, and i simple forget remove it, when patch his code.
2) Sorry, but your solution will not work in common case ;) Because strcmp is a not UTF-aware too.

If you want to patch this by normal way then you should use functions from mb_strings extension, for example (and check existence of this extension first). Another possible solution - usage of \Collator object, but PHP < 5.3 hasn't it.
I can implement this, but i have one question - for which reason you need this? All known (for me) GUI clients sort files in torrent before showing its.

**Comment by SteveMyers75** [comment]
It is vitally important to have it sort files when creating Partial Leeching Packs.

A lot of Private Trackers do not sort the file lists, and it is very difficult to use Pack torrents created in ruTorrent because of this.

Example: a "Partial Leeching Allowed" 500 File Pack that is  numerically named. 
001-Title One 
002-Title Two
....(and so on)
500-Title-Five hundred

Using ruTorrent, this file will be listed completely out-of-sequence because you can't set the Preserve File Order like you can in uTorrent.
Example filer order:
243 - Title Two Forty Three
011 - Title Eleven
097 - Title Ninety Seven
.... and so on.

Now imagine the pain for the use if he/she only wants to download files 200 to 225.... 
With ruTorrent, they would have to search the entire 500 file torrent and seek out the files all out of sequence.

In uTorrent with "Preserve File Order" on, they would just scan down to 200 and grab the file in sequence.

What most people I know that work with large Pack collections on seedboxes do is create the torrent in uTorrent, then load that into ruTorrent so it is in order.

It would be much easier in ruTorrent could just sort them...

**Comment by Novik** [comment]
> With ruTorrent, they would have to search the entire 500 file torrent and seek out the files all out of sequence.

With ruTorrent you press on the header of 'Name' column and have a sorted list of files.

**Comment by SteveMyers75** [comment]
Sorry, I should have said "with ruTorrent created torrent files, the user has to scan the entire list to locate the files they are looking for..."

You are talking about after you have already downloaded the torrents, I'm speaking about when the user is  looking for the files in different Packs on the Private Trackers before they know which ones to download. 

This is very easy with uTorrent created Packs, very difficult with those created on ruTorrent.

**Comment by Novik** [comment]
> This is very easy with uTorrent created Packs, very difficult with those created on ruTorrent.

Configure corresponding ruTorrent plugin for usage external binary. mktorrent, for example.

**Comment by SteveMyers75** [comment]
I was looking for a way to make ruTorrent work better because most seedboxes have it available.
As it is, I'll just keep using uTorrent with "Preserve File Order" checked and be done with it.

Thanks Anyways!
