### ISSUE TITLE
Cannot import empty feed in RSS plugin

### ISSUE THREAD

**Issue by Daiyousei** [Novik/ruTorrent#1068]
When I try to import a valide but empty feed (like this one https://aperture-sc.net/test.rss) I have the error : "Error loading feed : https://aperture-sc.net/test.rss".

I use rutorrent 3.7

After some searchs, I found it's because the plugin search for some "\<entry>\</entry>", but as the feed is empty (for now), there isn't any. The test at line 170 of the file "ruTorrent/plugins/rss/rss.php" fails, returning false, and trigering the "Error loading feed".

a solution could be to returne true if the "$ret" value is equal to 0, but not equal to false.

Could you please fix this ?

Edit : version

Edit 2 : I think the commit 7db9423b86d92d2c4b7f7f72d983c68a0a19579c broke the import of empty feeds. since this commit, we check if there is elements before importing ("!empty($this->items)" line 299 of "ruTorrent/plugins/rss/rss.php")

**Comment by Daiyousei** [comment]
Fixed by pull request #1070

**Comment by jumperalex** [comment]
I may be wrong but this seems to be back again in some form. I could not add an RSS bookmark feed that was empty. 

I removed the "bookmarks=on" portion of the url and I was able to add the feed which then listed the tracker's torrents, not just my autobookmarks. I put "bookmarks=on" back in the feed, it failed again, and removed the feed completely. 

Then I added a bookmarked torrent on my tracker's site. I was then able to add the feed to ruTorrent and it worked as expected by displaying that single bookmarked torrent. 

Finally I removed the torrent from my bookmarks and waited for the feed to update. On next update it popped an "error loading" message but at least it didn't delete the RSS feed. I actually noticed this behavior a while back but didn't much care because my feed was working when there were things to download. This time I had to regenerate my entire ruTorrent install (a docker) and the above all happened.

I'm using 3.7 and the link is in the form of https://revolutiontt.me/rss.php?feed=dl&bookmarks=on&passkey=

**Comment by Novik** [comment]
Try to see the source of feed.

**Comment by jumperalex** [comment]
I'm not sure what you mean. Do you mean view the feed url in my browser? Did that works fine. Or do you mean the source html returned? If so, here is a blank one:

`<?xml version="1.0" encoding="windows-1251" ?>`
`<rss version="2.0">`
`<channel>`
`<title>Revolution</title>`
`<link>https://revolutiontt.me</link>`
`<description>RSS Feeds - RevolutionTT</description>`
`<language>en-usde</language>`
`<copyright>Copyright ? 2004 Revolution</copyright>`
`<webMaster>noreply@revolutiontt.me</webMaster>`
`<image><title>Revolution</title>`
`<url>https://revolutiontt.me/favicon.ico</url>`
`<link>https://revolutiontt.me</link>`
`<width>16</width>`
`<height>16</height>`
`<description>RSS Feeds - RevolutionTT</description>`
`</image>`
`</channel>`
`</rss>`

and here is one with a single torrent listed

`<?xml version="1.0" encoding="windows-1251" ?>`
`<rss version="2.0">`
`<channel>`
`<title>Revolution</title>`
`<link>https://revolutiontt.me</link>`
`<description>RSS Feeds - RevolutionTT</description>`
`<language>en-usde</language>`
`<copyright>Copyright ? 2004 Revolution</copyright>`
`<webMaster>noreply@revolutiontt.me</webMaster>`
`<image><title>Revolution</title>`
`<url>https://revolutiontt.me/favicon.ico</url>`
`<link>https://revolutiontt.me</link>`
`<width>16</width>`
`<height>16</height>`
`<description>RSS Feeds - RevolutionTT</description>`
`</image>`
`<item><title>Brief.Encounters.S01E06.1080p.HDTV.x264-MORiTZ</title>`
`<link>https://revolutiontt.me/download.php/04VVXtQ9dxR/Brief.Encounters.S01E06.1080p.HDTV.x264-MORiTZ.torrent?passkey=xxxxxxxxxxxxxxxxxxx</link>`
`<description>`
`Category: TV/HDx264 `
` Size: 2.28 GB`
` Status: 3 seeders and 2 leechers`
` Added: 2016-08-08 17:04:46`
` Description:`
` Brief.Encounters.S01E06.1080p.HDTV.x264-MORiTZ`

`Date..........: 08/08/16`
`Resolution....: 1920x1080`
`Framerate.....: 25.000`
`CRF...........: 17`
`Video.bitrate.: 6 963 Kbps`
`Audio: AC-3 2.0 @ 192 Kbps`
`Subtitles: No`
`Duration......: 00:45:41.368`
`Size: 2.28 GiB`
`IMDb..........: http://www.imdb.com/title/tt5256926/`
`Pack..........: 50x50MB`
`</description>`
`<pubDate>Mon, 08 Aug 2016 17:04:46 -0400</pubDate>`
`</item>`
`</channel>`
`</rss>`

**Comment by NChief** [comment]
I have the same problem with an other tracker.
