### ISSUE TITLE
3.8 release soon?

### ISSUE THREAD

**Issue by Micdu70** [Novik/ruTorrent#1137]
Hello @Novik,

Do you plan to release ruTorrent v3.8 soon? (estimation)

**Comment by jollyroger** [comment]
+1 Any info on upcoming tagged release is welcome.

**Comment by enoch85** [comment]
@Novik Please release 3.8. It's needed for PHP7. Thanks for the best torrent solution on the market!

**Comment by tuxayo** [comment]
At least some packagers are still considering 3.7 as the latest release:
https://aur.archlinux.org/packages/rutorrent/
https://synocommunity.com/package/rutorrent

Given that there is no release since Apr 10, 2015, should it be considered that the master branch is now the release channel of rutorrent? If it's stable enough that's not an issue and less burden but an official statement is needed so people wanting to package rutorrent would track master.

**Comment by ss23** [comment]
@Novik Any updates on doing a release? Just a git tag is probably enough for now :)

**Comment by Micdu70** [comment]
ruTorrent 3.8 released: https://github.com/Novik/ruTorrent/releases/tag/v3.8
