### ISSUE TITLE
Size of "Add Torrent Window"

### ISSUE THREAD

**Issue by dannyti** [Novik/ruTorrent#1201]
Added a label suite. The url add button gets hidden away. 

Reference: http://imgur.com/a/b0DjU

Any hints to make the size of "add torrent box" bigger will be highly appreciated. 

I think a couple of px increase on either side should be sufficient. 

Thanks.

**Comment by Novik** [comment]
What about browser, client-side OS, ruTorrent version?

**Comment by dannyti** [comment]
Firefox , Windows, 3.7
The window doesnt expand even after highest resolution to accomodate all of that data into the window.

**Comment by dannyti** [comment]
This can be increased by editing
rutorrent/css/style.css - Line 250 ; replacing 290px to 330px

**Comment by virgo77** [comment]
Hi!
I found why it's going outside the window: it's because of the fourth checkbox at the top of the window which is taking two lines.

@dannyti  gave a good tip, and it saved my life ^^

However -and because the window was not really a beautiful one- I think this one is better: either changing the height, change only the width to 390px, so the text of the fourth box will stay in one line and the 'add' button will reappear :)
Line 251 (today's CSS file):
> div#tadd {display: none; **width: 390px**; height: 295px; left: 100px; top: 100px; position: absolute; margin: 0 auto }

Maybe Novik can adapt the css file in a next update?

Thanks a lot.

**Comment by koblack** [comment]
Update style.css b67b66dec473fe456868a5f27dfa1ba3e63f67d7
