### ISSUE TITLE
rutorrent won't work on firefox since v45

### ISSUE THREAD

**Issue by gputier** [Novik/ruTorrent#1229]
I just made a fresh install, just copy and past.
Same problem. So no, the problem is not my fault.
Rutorrent bugging until firefox v45
No problem with chrome or opera.

**Comment by exrat** [comment]
fresh install for me too and no problem with Firefox 45.0.1

**Comment by gputier** [comment]
I just back to v44 and i have no problem.
All problem are with french people atm.
All my friends have the same problem.

**Comment by Novik** [comment]
Yet once. This is a problem of *your* browser. Try to remove add-ons, extensions, disable adblock etc.

> All my friends have the same problem.

I can't see anyone exclude you with such problem.

**Comment by gputier** [comment]
i do not have addon! i installed firefox for test because so many french people have this problem atm !
i have no addon, no extension;
When im using v44, i do not have any problem.
I just reinstalled v45 and i have now the problem.
stop stuffiness and believe me.

**Comment by Tokyx** [comment]
Hi,
Firefox v45.0 for me too.
Can't access to ruTorrent WebUI.

Error log :
[29.03.2016 11:45:36] WebUI started.
[29.03.2016 11:45:37] Bad response from server: (0 [error,getratios])
[29.03.2016 11:45:37] Bad response from server: (0 [error,list])

No problem with other brothers.

**Comment by Meutledaron** [comment]
Hi men,

I have exactly the same problem only with firefox 45.0.1 ! 
No prob with chrome...

Help help :'(

**Comment by xombiemp** [comment]
I tested Firefox 45.0.1 and it worked fine for me using httprpc and traffic.  I even changed the language to French and it still worked.  You're going to have to try to eliminate variables to isolate where the problem is coming from.  Make sure you are using the latest from git, try on a new machine with a fresh install of Firefox, etc.

**Comment by gputier** [comment]
No need to be a prodigy .
V44 it work .
V45 it does not work .

So an update in Firefox causes this problem. Which ? I do not know , it's not my job to adapt a tool that is not mine with another tool that is not mine either.

I'd go to pick on the Firefox team but they seem to defeat the balls ;

As rutorrent is changed with a fresh version of GitHub , there is the same problem. Stop taking us for idiots 5 minutes, it's not the first time we use rutorrent .

Then I see that the French have a problem, and English , no.

Nothing shocks you ? 
https://gyazo.com/6a166e5139b9150e19f6a0ec6f0f6b4f
https://gyazo.com/b11ea926c2cd65191b10e93acd457a6a

"You're going to have to try to eliminate variables to isolate where the problem is coming from. Make sure you are using the latest from git, try on a new machine with a fresh install of Firefox, etc."

Done, Problem is on firefox, v45 only.
Tested on fresh install of Windows, same problem

**Comment by Novik** [comment]
> I do not know , it's not my job to adapt a tool that is not mine

Just for clearance.

1) I can't reproduce your problem.
2) This is *your* problem, not mine.
3) I don't owe you anything.

**Comment by gputier** [comment]
Ok, so u just an asshole ;)

2016-03-29 20:02 GMT+02:00 Novik <notifications@github.com>:

**Comment by Novik** [comment]
Fuck off, my dear french friend.

**Comment by manasb** [comment]
classic internet discussion lol 


# ask firefox devs, gputier? 
I don't know what you mean when you say "I'd go to pick on the Firefox team but they seem to defeat the balls ;"
I would look at web server log files for errors, assuming you are logging anything at all.

I've had an issue when using lighttpd & rutorrent, accessed through firefox or chromium; Torrent files would not upload. It was fixed by switching to nginx. I haven't tested apache.

Check your web server log files if possible, maybe something is producing errors/warnings there.
