### ISSUE TITLE
Error loading feeds RSS problems with https

### ISSUE THREAD

**Issue by evantingfox** [Novik/ruTorrent#1247]
Version rtorrent 0.9.6 rutorrent 3.7
cURL can get the right information from HTTPS RSS link.
However, the RSS plugins failed to load RSS link with https.
I can't add torrent link with https download link either.
But the RSS plugins can get the feeds from HTTP RSS link.
I don't know what's wrong with it.
Is there any specific error logs about the RSS plugins so I can check what is the problem?

**Comment by MorphyDK** [comment]
I have the exact same problem. 
SynoCommunity version though 3.7.8

Can add manually torrents - Http and https, not a problem. 
Once adding RSS feeds - errors on both http and https.
Read/write on /volume/web/rutorrent folder for 755
Checked and rutorrent got access to curl.

Dont got a clue how to fix it :(

**Comment by MorphyDK** [comment]
I had the exact same issue - got it working with an older version of rutorrent snoopy.class.inc

http://s000.tinyupload.com/index.php?file_id=55052263713770627460

Try it and see if this solve your problem - Did for me. 

The only problem I now have is - that RSS feeds dont auto update :(

**Comment by adam900710** [comment]
Confirmed the problem.
Using git version, commit a096fcc.

Older Snoopy fixes the problem.
@MorphyDK Although the rss feeds also updates.
I checked the mtime of the cache files, they all works correctly.

So it should be Snoopy problem.

**Comment by adam900710** [comment]
Further info:

I modified Snoopy's proxy_host and proxy_port to use my privoxy proxy.

Although manually update the RSS works and privoxy records the access, the intervally update only passes http request to privoxy, and https request doesn't even reach privoxy.

So there is definitely something wrong with Snoopy used in latest rutorrent.

**Comment by MorphyDK** [comment]
Got my RSS feed fixed :) . It was a permission issue :) . Rutorrent User had to have access to a folder under shares. All good. Still the snoopy is messed. Using the old one . Running perfectly now . :)

**Comment by Fugor** [comment]
@MorphyDK

Could you detail the permission/owners your have under /share ?

I have the same issue since a while now.

**Comment by MorphyDK** [comment]
Hi Fugor.

Sure :)

This is on my Synology NAS where rutorrent is the user and http is my webserver user.

Goto /share/settings

the "rss" folder give 777 and give access to rutorrent:http 

Solved my problems :)

**Comment by anoma** [comment]
Can we reopen this ticket please.

**Snoopy.class.inc** is very broken since these commits for some SSL RSS and when hit you have no choice but to revert to make it work:

Working for those having issues:
https://raw.githubusercontent.com/Novik/ruTorrent/36cdfc4cd92b5903c2f8bc8981ef05d3380d5b02/php/Snoopy.class.inc

**Comment by Pingblue** [comment]
This is still an issue with the latest version version of rutorrent from Github.

Cannot add feeds from TD until the older Snoopy.class.inc is used.

Apache/2.4.18
PHP 7.0

**Comment by ritewhose** [comment]
I've just spent a bit of today looking at the codebase so I could be wrong but here's my theory anyway:
In php/Snoopy.class.inc, line 457
`
$headers[] = "Host: ".$this->host.($this->port == 443 ? "" : ":".$this->port);
`
...should be changed to...
`
$headers[] = "Host: ".$this->host.($this->port == 443 ? "" : ":".$this->port)."\r\n";
`
The second adds the period and the newline. Without the newline I would expect the HTTPS requests to get mangled.

**Comment by ritewhose** [comment]
I was incorrect. Initially I didn't realize at first glance that _httprequest and _httpsrequest are fundamentally different. The problem for me was line 491:

`$cmdline_params = '-0';`

Commenting it out did the trick for me. When executing curl, it will throw a libcurl 56 error if you're downloading an HTTP/1.1 page even though the files download correctly. The return code causes the _httpserequest function to miss a whole bunch of important stuff due to the error handler on lines 519 and 520.

Seemingly, that line was put in to fix a problem with nginx (which I can't really test, I can't find any discussion on it -- my server is reporting server type cloudflare-nginx). Maybe HTTP/1.1 should be attempted first, and if it fails, fall back to HTTP/1.0. 

If it matters, curl is receiving the following error from GnuTLS:
`GnuTLS recv error (-110): The TLS connection was non-properly terminated.`
And that's setting the error code in curl to CURLE_RECV_ERROR (56). Maybe curl isn't terminating HTTP/1.0 connections over TLS correctly? I don't know of a server that uses HTTP/1.0 to test with.
