### ISSUE TITLE
ruTorrent forum.org not sending activation emails

### ISSUE THREAD

**Issue by DRanged1** [Novik/ruTorrent#1270]
I have tried repeatedly, with several different e-mail addresses, to get an activation e-mail sent from http://forums.rutorrent.org/ without success. There doesn't seem to be a way to contact an administrator, can anyone here help or get in touch with someone there who can? Without being activated, I can't post in the forum.

Thanks.

**Comment by Novik** [comment]
What about your email address?

**Comment by DRanged1** [comment]
I have tried several gmail.com addresses, both with and without punctuation in them, and two different yahoo.com adresses. Nothing works. No emails received at any address, and no way to alert anyone on the forum that their activation email feature is broken.

**Comment by Novik** [comment]
I need to know your email address for activate it manually.

**Comment by DRanged1** [comment]
Any way to do that privately? Can't anyone read this thread?

**Comment by DRanged1** [comment]
My user ID there is ChasVA, if that's helpful? Also, the e-mail address there is the same one I'm using here.

**Comment by Novik** [comment]
Activated.

**Comment by Papoulka** [comment]
Writing here because forums.rutorrent.org seems 'dead'.  Will be glad to know of a replacement.

Thanks very much for rutorrent.  I use it daily and it's great.

--> Is there a Paypal or Bitcoin donations page?

I have two suggestions:

1)  Even if I sort by a non-dynamic field like 'Label', the list of torrents constantly cycles, switching places.  This makes it hard to keep selections, step through torrents etc.  It would be great if this can be stopped.

2)  In torrent size fields I'd like'MB' to be presented in red, to be more distinct from 'KB'.  Or bold, or any other method.

Thanks again.

**Comment by OwnerCM** [comment]
> 您的电子邮件地址呢？

现在还能帮忙激活吗？也是收不到激活邮件
