### ISSUE TITLE
Error Rutorrent

### ISSUE THREAD

**Issue by sashimiz** [Novik/ruTorrent#1322]
Hi, please help me!!
Error in rutorrent :  (200 [parsererror,getplugins]) SyntaxError: expected expression, got '<'
                            : (405 [error,getuisettings]) <html> <head><title>405 Not Allowed</title></head> <body bgcolor="white"> <center><h1>405 Not Allowed</h1></center> <hr><center>nginx/1.10.1</center> </body> </html> 

Archlinux OS + nginx 

what is the solution?

thx

**Comment by Corin-EU** [comment]
I had a similar issue with Apache and the same error message.  The problem arises because your webserver is not processing the php code.  You need to check in your nginx configuration specific to rutorrent or the general all cases what you have configured under "location ~ \.php$" and if using fastcgi
the parameter fastcgi_pass.  This tells nginx where to send the php code for processing, eg if using php-fpm  daemon something like fpm-torrent

`` location ~ \.php$
        {
                include                         /etc/nginx/include/fastcgi.conf;
                ...
                fastcgi_pass                    fpm-torrent;
               ...
     }``

 and then a configuration file under nginx/conf.d defining what the handle fpm-torrent actually is, eg

`` upstream fpm-torrent
    {
   	server		unix:/run/php5-fpm/torrent.sock;
    }``

For a permission denied error, you must ensure that the nginx web server process (usually running as group www-data) has read/write permission to the socket, so it should be group owned www-data and group permission rw.  Obviously php-fpm has to be configured to create a "torrent" pool and associated socket.

**Comment by jkdf2** [comment]
The forums are gone forever so I'm glad that he asked here. I had this same problem on Debian Stretch and I agree it's a configuration issue. It helped me to get one thing up and running at a time: first nginx, then PHP-FPM, then finally ruTorrent.

[This guide](https://www.howtoforge.com/tutorial/installing-nginx-with-php7-fpm-and-mysql-on-ubuntu-16.04-lts-lemp/#-installing-php-) helped a lot.
