### ISSUE TITLE
Engine Torrent411.php doesn't work

### ISSUE THREAD

**Issue by gre1423** [Novik/ruTorrent#1453]
Everything is in the subject, it gives no result.

**Comment by FiFi5** [comment]
That's because the site and tracker URLs have changed twice over the last weeks.
Update Torrent411.php to put the new URL "www.t411.al" in. I have two occurences in my file, line 5 and 117.

` public $defaults = array("public" => false, "page_size" => 50, "cookies" => "www.t411.al|uid=xx42xxx;pass=xxxxxxxxxxxxxxxxxxxx;authKey=yyyyyyyyyyyyyy;authApi=zzzzzzzzzzzzz;");`

`$url   = 'https://www.t411.al';`

**Comment by gre1423** [comment]
Thanks, I tried your solution but it stil doesn't work. Did you test it ?

**Comment by FiFi5** [comment]
Yes it's working here, I have attached it. 
Also I have noticed that my authApi was different from the value I had already put in the files years ago, so you may want to check 
[Torrent411.php.txt](https://github.com/Novik/ruTorrent/files/980822/Torrent411.php.txt)

your cookies to make sure uid, pass, authKey and authAPI are all correct.

**Comment by BadFlo** [comment]
It used to work, but not anymore. Is it working for you guys?

**Comment by maxcore** [comment]
Use jackett!

**Comment by Kcchouette** [comment]
Please can you close this issue, @Novik, T411 has now closed as written in #1573
