### ISSUE TITLE
Broken rss torrent loader "Error loading torrent"

### ISSUE THREAD

**Issue by v-v** [Novik/ruTorrent#1462]
Hello,

in the latest version, the RSS manager won't be able to load the torrent on some trackers (e.g. torrentleech) and will report:

```
 [23.05.2017 11:20:54] Error loading torrent. (https://www.torrentleech.org/xxxxxxxxx.torrent)
````

This is caused by the "workaround for nginx" where curl is forced to use http 1.0:
https://github.com/Novik/ruTorrent/blob/master/php/Snoopy.class.inc#L483

Reverting line 483 in php/Snoopy.class.inc to:
`$cmdline_params = '';`
solves the problem.

I'm not aware of what problem you had with nginx but maybe the workaround could be made in such a way that it doesn't affect automatic downloading through RSS for some of us.

Thank you

**Comment by Bl0ub** [comment]
Careful because your file with your correction still has an issue for loading rss feed, i receive an Error loading feed when i try to load an rss fedd in https (it is working in http).
The only snoopy file which works for now is this one (from an older version) : 
http://s000.tinyupload.com/download.php?file_id=55052263713770627460&t=5505226371377062746065676

**Comment by v-v** [comment]
Oh, yeah, I didn't test rss fetching with https.

Thank you for the working snoopy file!
