### ISSUE TITLE
T411 in public Tracker

### ISSUE THREAD

**Issue by Matthe95** [Novik/ruTorrent#1545]
Does the tracker works for anyone on the extsearch?

I think it's because the tracker is not totally public. We need an inscription to download.

Would anyone have a solution? Because, actually the two main (ygg & t411) french tracker doesn't work on extsearch.

Thanks

**Comment by Micdu70** [comment]
T411 is a public tracker, no need to sign up to download torrents. But download links (torrent or magnet) are not available on search pages, and it's weird that this site uses "hash info" of torrents in download URL instead of their "torrent ID" in database...

YggTorrent requires to sign up to download torrents but their session's cookie(s) expire in 2 hours (no option to keep the session alive on login page). So we try to add YggTorrent account with "LoginMgr" plugin here #1536

**Comment by arnaudbey** [comment]
t411 has been shut down weeks ago btw ! :(

**Comment by Matthe95** [comment]
No, we speak about t411.si which is of course open.

**Comment by arnaudbey** [comment]
my bad ! didn't know they came back. Thanks !

**Comment by Matthe95** [comment]
No, we speak about t411.si wich is of course open. 

Envoyé de mon iPhone

**Comment by Kcchouette** [comment]
Please can you close this issue, @Novik, T411 has now closed as written in #1573
