### ISSUE TITLE
Confused about Autotools Templates

### ISSUE THREAD

**Issue by holygamer** [Novik/ruTorrent#1625]
Hi, I have autodl-irssi set to download Movies from IP Torrents to: rtorrent/data/Downloading/IPT/Movies. I also set it to label them as: IPT Movies
I have autodl-irssi set to download Games from IP Torrents to: rtorrent/data/Downloading/IPT/PC Games. I also set it to label them as: PC Games

I want Autotools to automatically move completed downloads for IPT Movies to rtorrent/data/Completed/IPT/Movies/
I want Autotools to automatically move completed downloads for IPT Games to rtorrent/data/Completed/IPT/PC Games/

How would I set that up in the Autotools?

**Comment by s-c-o-o-t** [comment]
Well you dont really want to use Move feature Because you need to leave the movie or game in the downloaded dir. Why *for seeding*. You might want to use the Copy Feature, once the file is downloaded from the tracker (ipt) to Finished dir. or downloaded dir which ever you want to call it. It will copy the Folder to another location like ex: /rtorrent/data/Completed/IPT/Movies/. With those folders you can even delete them , they are a copy of the original that is left in downloaded dir.  Here it is in the Options Menu, It works Very well with my settings, follow them and see what you get.
![screenshot_22](https://user-images.githubusercontent.com/28552644/34509933-4d1f5536-f015-11e7-97a4-c3ceb2b56d6d.png)
