### ISSUE TITLE
Ratio plugin - min AND time

### ISSUE THREAD

**Issue by inspectorgadjet7** [Novik/ruTorrent#1653]
Hi. It would be useful if the time option for the ratio plugin could be have a toggle for AND/OR. I would like to be able to remove torrents for certain trackers once the torrent has reached the minimum ratio AND only if it has been seeding for x hours. So for example, if my torrent reaches the minimum ratio, I would like it to keep going if it hasn't seeded for a week or two. This would mean my torrents always have to reach the minimum ratio but they could continue seeding for a while longer to get a better ratio.

**Comment by s-c-o-o-t** [comment]
![ratiogroups](https://user-images.githubusercontent.com/28552644/36075470-062f661a-0f15-11e8-92ae-700095600a70.png)

in rutorrent web interface settings --> ratio groups , the first line i have set alwready to automatically remove the rorrents that have been labeled tv-x264  Min% 120 which is 1:2 ratio max% 120 ratio , so that means you can set in action section to remove data / stop / pause / etc when it reaches 1:2 ratio, ustually you are suppostu seed to 1:1 you can set it to higher seeding for ex bonus point more upload credit etc before removing data from seeding folder. You can also have the torrent  you downloaded to copy to an  another dir .  that setting is in another location

**Comment by inspectorgadjet7** [comment]
I understand how that works. I think you misunderstood what I meant. I don't want it to perform an action immediately when only the min value is reached. I want it to check both the min value and time. So if it reaches 120% but it hasn't been seeding for 168 hours it will keep seeding. Only when it matches both min and time values I want it to stop.
Currently, if I set both min and time values it performs the action when it matches either one of the values.
