### ISSUE TITLE
how to make seed 15k

### ISSUE THREAD

**Issue by tashkas1** [Novik/ruTorrent#1702]
Hello, 
how to make rutorrent handle 15k torrents to seed? Max it can handle 6200 or more little bit.

**Comment by simshadows** [comment]
Is horizontal scaling an option? I don't have a tonne of torrents, but I have 5 different instances of rtorrent+rutorrent (each instance being for a different category of torrents). If you are finding a single instance to be limiting, more instances should in theory allow you to seed more on the same box. I don't have a tonne of torrents yet to say for sure though.

**Comment by tashkas1** [comment]
is there somewhere guide to creat separate instance?

**Comment by simshadows** [comment]
Not that I know of, but all my scripts and edits are available in [my personal fork of this repository](https://github.com/simshadows/rutorrent-myconfig/tree/myconfig/myconfig). Although admittedly, I'll need to work on making it more user-friendly. I might do that on the next release of rutorrent.

My [setup script](https://github.com/simshadows/rutorrent-myconfig/blob/myconfig/myconfig/scripts/setup-instance.sh) outlines most of the steps I use to set up an instance. You'll also need to use my custom copy of [config.php](https://github.com/simshadows/rutorrent-myconfig/blob/myconfig/conf/config.php) since I pass the configuration parameters for rutorrent in from the webserver.

Also, you'll need to edit `nginx.conf`, so here's my copy of it:

```
user www-data;
worker_processes auto;
pid /run/nginx.pid;

events {
	worker_connections 768;
	# multi_accept on;
}

http {
	include /etc/nginx/mime.types;
	default_type application/octet-stream;

	sendfile on;
	tcp_nopush on;
	tcp_nodelay on;
	keepalive_timeout 65;
	types_hash_max_size 2048;
	# server_tokens off;

	# server_names_hash_bucket_size 64;
	# server_name_in_redirect off;

	################ 
	# SSL Settings #
	################ 

	ssl_protocols TLSv1 TLSv1.1 TLSv1.2; # Dropping SSLv3, ref: POODLE
	ssl_prefer_server_ciphers on;

	####################
	# Logging Settings #
	####################

	access_log /var/log/nginx/access.log;
	error_log /var/log/nginx/error.log info;

	#################
	# Gzip Settings #
	#################

	gzip on;
	gzip_disable "msie6";

	#############
	# rutorrent #
	#############
	
	server {
	listen       80;
        server_name  localhost;
        root         /usr/share/nginx/html/;
	include /mnt/drive0/rtorrent/instance-public0/instance-config/nginx-instance-config;
	include /mnt/drive0/rtorrent/instance-red0/instance-config/nginx-instance-config;
	include /mnt/drive0/rtorrent/instance-nw0/instance-config/nginx-instance-config;
	include /mnt/drive0/rtorrent/instance-red1/instance-config/nginx-instance-config;
	include /mnt/drive0/rtorrent/instance-nw1/instance-config/nginx-instance-config;
	}
}
```

Hopefully, that should give you an idea of how to configure your seedbox.
