### ISSUE TITLE
Throttle incorrect speeds

### ISSUE THREAD

**Issue by rezad1393** [Novik/ruTorrent#1819]
I recently seen an issue with correct speed in rtorrent/rutorrent throttle.
when I set the channel for a torrent with a speed higher that the global speed limit for all rtorrent then the speed of that torrent is neither the global one nor the channel one.

for example if I put global speed at 600KB/s and set no channel for a torrent I get the 600.
 if I put no global speed limit and set 600KB download channel for a torrent I get the 600.
 if I put global at 600 and channel at 500 i get 500 for the torrent.
but if I put global at 600 and channel at 800 I get 400.
why?

**Comment by zotteken** [comment]
I appear to be having similar issues.
I have no global speed limit set, so throttle has it set to 327625KiB/s.
That gives amazing speeds (I have seen up to 100MiB/s), but it causes enormous lag.
So I decide to limit the torrents with loads of seeders speed limit to a mere 256KiB/s (channel 10).
Now it appears this influences the global speed limit, since total download speed doesn't want to go above 256KiB/s.
