### ISSUE TITLE
Moving torrents using Fast Resume deletes the torrent-data from disk. 

### ISSUE THREAD

**Issue by smathev** [Novik/ruTorrent#1853]
Hi all.

I'm having a weird issue, which I don't know how to fix or even troubleshoot.

Using the latest rtorrent and ruTorrent in the docker from [romancin](https://github.com/romancin/rutorrent-flood-docker) it seems that if I move a completed (downloaded) torrent from one location to another (on the same disk) rTorrent deletes the downloaded file, and moves the download location, and then starts redownloading the file.

The torrent goes from 100% to 0% and starts downloading again. Searching for the data, I find that the data is gone from the disk too .

When I disable the Fast Resume option during a move, the file is moved without issue and the torrent stays at 100%.

It's irritating to say the least to have to remember to disable the option everytime I move a file, so if there simply was a way in the rtorrent.rc to disable the option as standard that would be great.

Thanks in advance.

I originally made the issue in [rtorrent on Github](https://github.com/rakshasa/rtorrent/issues/852), but was referred here.

**Comment by bavis-m** [comment]
Ran into this using a different container: https://github.com/crazy-max/docker-rtorrent-rutorrent. The issue was the default rtorrent.rc (not sure if one is included in this project) was set to erase torrent data when the `d.erase` is called on a torrent. The `datadir` plugin in rutorrent erases the old torrent file before adding the new file (adding the torrent as a totally new file with data already existing is how it implements fast resume). Perhaps your config contains the same logic?

**Comment by smathev** [comment]
Hi @bavis-m 

Thanks for getting back to me, I had accepted that fast resume just wasn't for me - but getting your feedback led me to investigate. 
This is the only place erase is used 
```
#Erase data when torrent deleted (no need erasedata plugin on ruTorrent)
#method.set_key = event.download.erased,delete_erased,"execute=rm,-rf,--,$d.data_path="
```
I'm unsure if the datadir plugin is something I could disable, so I don't know if there is anything else I need to check?

Either way, thanks for your input - but I don't think that's the issue :/

**Comment by n1ce-0ne** [comment]
i share an interest in this kind of thing, fast resume can be troublesome to say the least, ive had issues in the past,
not with files being deleted but other issues like updating the os stopped it working etc.

its something some see in a dark light the whole fast resume ideology, in the end i scrapped using it,

my suggestion atm, you will either have to start spending hours trying to figure it OR better still try figure a way of not needing it like dont move the files just grab them to that location in the 1st place etc

my thoughts is maybe fast resume is erroring out due to confusion about the locations & stopping the moving script from doing its job, ie
1)files are taken from dir1 but whilst moving to dir2 & creating the new torrent file an error halts proceedings thus the files are never sent to dir2, even tho the new torrent file was created & sent to rtorrent the moving script didnt like something & got corrupted by fast resume.

if i remember rightly last time i was debugging fast resume i started right back at the drawing board with things to try work out how far the fast resume script got b4 it stopped by having it save like test files at each section, like echo test1.txt > /home/user at line 20 then echo test2.txt > /home/user at line 40 etc etc etc then once tested check out /home/user & see how far it got :)

all depends how much time you have & how much you need fast resume :)

like if the files are only a few gb then maybe just ditch it :)

**Comment by bavis-m** [comment]
@smathev That line probably *is* causing the problem. The datadir script, when fast resume is selected, works by *erasing* the old torrent, moving the files, and then recreating the torrent with fast resume data set. I'm not sure why it has to work this way; I'm not an expert on libtorrent internals, but maybe fast resume data can't be setup on a live torrent in the way needed, this is likely a question for @Novik. I think an appropriate bandaid fix would be a patch to libtorrent/rtorrent that adds a command `erase_no_event` or some such that stops that line in your config from firing. The intent of the plugin isn't to actually remove the torrent as that event suggests, but just give to the appearance of having moving it by deleting and recreating it.

**Comment by smathev** [comment]
@bavis-m 

Oh, yeah. No, I'm sorry for not being clear.

The two lines are the only place erase is mentioned in the rtorrent.rc and they are commented out. So, I wouldn't think they are being used as is. I've sort of accepted that fast resume doesn't work - and I don't know what I'm missing. I, depending on size of the file, just move it without fast resume in rutorrent - or move it manually from linux-shell and then point the torrent datadir to the new location.

@n1ce-0ne - yeah, like you suggest, is basically what I've resigned to. Not using fast resume.

My main problem now is basically:
"How do I disable fast resume being auto-enabled everytime I want to move a torrent-file?" :)
