### ISSUE TITLE
can't access pgrep/python

### ISSUE THREAD

**Issue by ghost** [Novik/ruTorrent#1900]
Hello

My rutorrent installation seems to be unable to access some programs. I was able to fix curl and php via the conf/config.php (even though they were in $PATH but i still get the following error message:

`[25.06.2019 16:03:15] WebUI started.
[25.06.2019 16:03:15] _task: Plugin will not work. Webserver user can't access external program (pgrep).
[25.06.2019 16:03:15] _cloudflare: Plugin will not work. Webserver user can't access external program (python).
[25.06.2019 16:03:15] create: Plugin will not work. It requires plugin(s) _task
[25.06.2019 16:03:15] unpack: Plugin will not work. It requires plugin(s) _task
[25.06.2019 16:03:15] mediainfo: Plugin will not work. It requires plugin(s) _task
[25.06.2019 16:03:15] screenshots: Plugin will not work. It requires plugin(s) _task
[25.06.2019 16:03:15] spectrogram: Plugin will not work. It requires plugin(s) _task`

`# sudo -u www-data pgrep
pgrep: no matching criteria specified
Try `pgrep --help' for more information.`

seems to work, any advice would be apreciated

**Comment by cmasdf** [comment]
Same issue here, using revision 85d7a4f02ad1e89833285ec662a753f7f304e81e with php7.3 and debian bullseye.

**Comment by ascent12** [comment]
I'm not sure why it doesn't find anything in PATH, but adding more entries to `$pathToExternals` in config.php fixed it for me:
```php
$pathToExternals = array(
	"php" 	=> '/usr/bin/php',			// Something like /usr/bin/php. If empty, will be found in PATH.
	"curl"	=> '/usr/bin/curl',			// Something like /usr/bin/curl. If empty, will be found in PATH.
	"gzip"	=> '/usr/bin/gzip',			// Something like /usr/bin/gzip. If empty, will be found in PATH.
	"id"	=> '/usr/bin/id',			// Something like /usr/bin/id. If empty, will be found in PATH.
	"stat"	=> '/usr/bin/stat',			// Something like /usr/bin/stat. If empty, will be found in PATH.
	"python" => '/usr/bin/python2',
	"pgrep" => '/usr/bin/pgrep',
);
```

**Comment by XANi** [comment]
@ascent12 quite simply because there is no $PATH variable set to be look in

Quick fix:

* go into PHP-FPM instance config - /etc/php/7.3/fpm/pool.d/www.conf ) if you are using php7.3 for example
* add, at the end:
 `env[PATH] = /sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin`
* restart php - `systemctl restart php7.3-fpm`

Proper fix would *probably*  be looking in `/usr/bin` if 

* path to tool is not set
* `PATH` env variable is not set

that should make it work out of the box on newer systems
