### ISSUE TITLE
Make new release

### ISSUE THREAD

**Issue by ghost** [Novik/ruTorrent#1919]
Due to the way many dockerfiles are built (popular one being linuxserver/rutorrent), the recent (3 days ago) update to rtorrent breaks rutorrent.

rutorrent needs a github release with this fix, because as of right now those docker images are broken with a mismatch between rutorrent and rtorrent.

**Comment by Novik** [comment]
Tommorow author of rtorrent make yet one good change (as this already was happens several times).
And? I will need to make new release again?
Why you (or anyone) can't make new docker container from the current ruTorrent master?

**Comment by Novik** [comment]
Is pre-release good for your purposes?

**Comment by LooseSeal2** [comment]
I'm sure a pre release will benefit some docker images

This is a broader issue, an going one, like you said. The only way to mitigate this for everyone, is to make a release when this situation happens, as most people wouldn't want to run off master (I don't mind but I'm a dev too).

I understand this can be tricky because there's been some commits some April that you may not want to push out yet until you are ready. For that situation, if that's your concern, you can make a patch release that just includes the API bump or fix needed.

I'll try to nudge the linuxserver team to provide a master tag for their image

**Comment by Novik** [comment]
https://github.com/Novik/ruTorrent/releases/tag/v3.10-beta

**Comment by aptalca** [comment]
@Novik 
My two cents, this isn't just about the docker image. This is about your latest stable build not being compatible with the latest stable rtorrent. It affects all of your users who are using your latest stable on alpine or any other distro where rtorrent got updated to the api changing build or higher.

You may not want to publish new stable releases to fix breaking api changes, that's your decision, but keep in mind that it affects bare metal users as well, not just docker users. As a user, I tend to stick with stable releases if they are offered, which the readme clearly lists both stable and dev versions.

**Comment by thelamer** [comment]
@Novik We will continue to build from your stable releases, and use rtorrent from the Alpine repos. https://pkgs.alpinelinux.org/packages?name=rtorrent&branch=v3.10

I leave it to your discretion to tag stable releases on this footprint of users. (currently 38 million Docker pulls)
