### ISSUE TITLE
"Tracker" section in torrent overview is never populated

### ISSUE THREAD

**Issue by ThatNerdyPikachu** [Novik/ruTorrent#1982]
![yhpyos3l](https://user-images.githubusercontent.com/15848969/71129875-7f367680-21be-11ea-95e6-64d613695106.png)

**Comment by Novik** [comment]
1) Tracker status will be populated, when you will have it. For example, as message about tracker error.
2) Tracker URL will not be populated in the modern versions of rTorrent. Because corresponded function 'd.tracker_focus' was removed in this - https://github.com/rakshasa/rtorrent/commit/ed6182589ad28c861d62e025368b83158a608679#diff-65c4a834a788a1781f65073525ae343b commit.
