### ISSUE TITLE
check-port plugin status unknown

### ISSUE THREAD

**Issue by chrcoluk** [Novik/ruTorrent#2116]
On both portchecker and yougetsignal

Someone made a patch on older rutorrent that works with canyouseeme but I dont know how to add that to latest rutorrent.

The port is open, manually tested.

**Comment by Novik** [comment]
1) With default configuration option ($useWebsite = "yougetsignal") plugins works good without any changes. Doublecheck  your port and ruTorrent state.
2) With alternative engine ($useWebsite = "portchecker") plugin do not works due to changes on the https://portchecker.co. I made corresponding changes in the plugin's code and now it works good to.

**Comment by chrcoluk** [comment]
I am technically competent and can confirm the port is open, if I use the patch on older rutorrent it also shows as open.

However I will check your fixes to portchecker.co and hopefully that one now works, I will report back on it. Thanks
