### ISSUE TITLE
Modern design

### ISSUE THREAD

**Issue by sinnlosername** [Novik/ruTorrent#2126]
I think it would be nice if ruTorrent got a more modern design. By that I mean for example less shadows or flat icons. 
Also I think this would be an improvement upon the already existing main feature of a quote:
> - Nice look ;)

If you are interested in this I can help with this.

**Comment by Novik** [comment]
Try to see on the plugin ```Theme``` - https://github.com/Novik/ruTorrent/wiki/PluginTheme

> If you are interested in this I can help with this.

Of course.

**Comment by sinnlosername** [comment]
what do you think of this?
![screenshot](https://user-images.githubusercontent.com/17328331/102018446-91b1a480-3d6d-11eb-92d4-605ddd06fb35.png)
 a few icons are from flaticon, would have to attribute them

**Comment by Gosokan** [comment]
> what do you think of this?
> ![screenshot]
> a few icons are from flaticon, would have to attribute them

I thinks is more better if rutorrent can have resposive layout rather than just changing icons. 
Or at least just make a panel on the left side (div#Catlist) can be collapsed [example](https://www.w3schools.com/howto/howto_js_collapse_sidebar.asp).
And  also with div#tdetails, maybe a dynamic tabs can be used for this [(example)](https://www.w3schools.com/bootstrap/tryit.asp?filename=trybs_ref_comp_nav-toggle&stacked=h).

**Comment by Novik** [comment]
> I thinks is more better if rutorrent can have resposive layout rather than just changing icons.

All in your hands. 

> Or at least just make a panel on the left side (div#Catlist) can be collapsed example.

Try to press F7. Or press F1 and see all bindings.

> And also with div#tdetails, maybe a dynamic tabs can be used for this 

We already have dynamic tabs. What do you mean?
