### ISSUE TITLE
Concern about ambigous rtorrent fork

### ISSUE THREAD

**Issue by zawapete** [Novik/ruTorrent#2177]
At https://github.com/jesec/rtorrent you can find a kind of fork, with no clear statement about its nature and relation with the original project, aiming on the paper to improve RPC interfaces and other optimistation.

I'm rather concerned since the maintainer proofed on other project to be uncaring about community and to be rather following its own development agenda.

Which of the two versions (if not both) will the ruTorrent's developers plan to support in the future?

**Comment by Novik** [comment]
> At https://github.com/jesec/rtorrent you can find a kind of fork

Now ruTorrent is not compatible with this fork. 
If you want use it you should comment this fragment - https://github.com/Novik/ruTorrent/blob/master/php/settings.php#L232-L244

> Which of the two versions

I have my own fork with a set of security patches - https://github.com/Novik/rtorrent 
It disable usage of several dangerous commands (like 'execute') for configuration rtorrent + ruTorrent + httprpc plugin.
And, of course, it also haven't clear statement about its nature and relation with the original project ;)

> will the ruTorrent's developers plan to support in the future?

Right now I haven't such plans. Because rtorrent project seems like abandoned and dead.

**Comment by zawapete** [comment]
>And, of course, it also haven't clear statement about its nature and relation with the original project ;)

it has: it's clearly a github fork of the original project :)



>> will the ruTorrent's developers plan to support in the future?

> Right now I haven't such plans. Because rtorrent project seems like abandoned and dead.

ruTorrent seems to still be active and maintaned, am I wrong?
how does this match the fact that "rtorrent project seems like abandoned and dead"? :)

Any interest in reaching the original rtorrent's maintainer for revamping the project? even only for pushing upstream your fork improvement?

regardless of the status of the project, rtorrent has still a huge adoption, as well as ruTorrent. I would be glad to partecipate in any way I could help
