### ISSUE TITLE
Ratio plugin does not erase unpacked data (set to "Remove data (All)")

### ISSUE THREAD

**Issue by defhead** [Novik/ruTorrent#2186]
Hello,
![image](https://user-images.githubusercontent.com/24367728/120885102-5e96f200-c5e7-11eb-98f5-029b765674fd.png)
I assumed this enhancement https://github.com/Novik/ruTorrent/pull/1023 was supposed to allow to erase the unpacked files with the ratio plugin.
Currently, it erase only torrent-linked files and leaves the unpacked data.

I checked the user permissions and ownership, the unpacked data has the same ones the torrent files have.

Does someone has any idea how it can be fixed?
Thank you.

**Comment by Novik** [comment]
Two possible cases.
1) You do not enable 'remove data (all)' mode in the erasedata plugin. In the erasedata/conf.php you should have ```$enableForceDeletion = true;``` 
(Of course, this is not good style of programming, because plugin 'ratio' must check this situation, but we have what we have...)
2) Something bad with permissions. Can rtorrent user delete these files at all?

**Comment by defhead** [comment]
It's weird. I read the ratio plugin code but didn't see any relation with the erasedata plugin.
I'll set this boolean to TRUE (it was set to false), but I'll have to wait few days to confirm it fixes my issue.

Once unpacked, the file has the same User and Group ownership, and the same permissions than the torrent files, which are successfully deleted by rtorrent user everytime.
