### ISSUE TITLE
Port Check Plugin (Bad Responce From Server)

### ISSUE THREAD

**Issue by ADz-83** [Novik/ruTorrent#2223]
Getting following on all ruTorrent installs with port check plugin..
Bad response from server: (200 [parsererror,initportcheck]) { "ip: "?.?.?.?","port": xxxxxx, "status": 0 }

**Comment by koblack** [comment]
https://ports.yougetsignal.com/check-port.php
`{"status":"failure","message":"System temporarily offline due to heavy load."}`

**Comment by Micdu70** [comment]
@ADz-83 Hello, check if you can access this page: [https://www.yougetsignal.com/tools/open-ports/](https://www.yougetsignal.com/tools/open-ports/). If you can't access it then you must edit the `conf.php` file (for the `port_check` plugin) in order to use "portchecker" (instead of "yougetsignal"). ;)

Anyway, this "Bad response from server" should never appear and it will be fixed with my PR #2224. :)
