### ISSUE TITLE
Why each version of rutorrent have problems on master branch ?

### ISSUE THREAD

**Issue by Whisper40** [Novik/ruTorrent#2302]
I don't understand why your master branch have problem everyday..
I'm not sure that commit on master branch are tested before being pushed..
Please, can you test more your changes..

Today, on master branch : 
```
Uncaught TypeError: theWebUI.createSelectableLabelElement is not a function
Uncaught TypeError: theWebUI.updateAllFilterLabel is not a function
Uncaught TypeError: theWebUI.updateLabel is not a function
```

**Comment by stickz** [comment]
Okay, I fixed the problem with the master branch. The user is not allowed to create blank issue reports anymore. They must use one of our new templates. Also it's required to check off they've **cleared their web browser cache** before clicking submit.

**Comment by henning-schild** [comment]
I am currently trying to get an updated version of rutorrent into gentoo linux and found this issue because a tester maybe ran into this one.

@stickz can you give a clue on that fix so i can cherry-pick or wait for an upcoming release.

Or maybe give advice on how to prevent caching issues, especially when upgrading from one release to another.
