### ISSUE TITLE
Err: Icons are showed wrong

### ISSUE THREAD

**Issue by hassonipulus** [Novik/ruTorrent#2357]
### Please complete the following tasks.

- [X] Web browser cache cleared
- [X] Link provided to install script if applicable
- [X] Web browser, ruTorrent, PHP and OS version provided

### Tell us about your environment

 Web Browser: Firefox
ruTorrent: v4.0-beta.1 OR Master: fc9d1f0
PHP: PHP 7.4.3
OS: Ubuntu 20.04.3 LTS

### Tell us how you installed ruTorrent

Swizzin

### Describe the bug

https://i.imgur.com/nlPJ2k3.png

### Steps to reproduce

Perform clean install

**Comment by hassonipulus** [comment]
> Hi @hassonipulus , I would strongly recommend upgrading to [v4.0-beta.2](https://github.com/Novik/ruTorrent/releases/tag/v4.0-beta.2).
> 
> Please let me know if this resolves your problem. This version is more stable and bug free.

Unfortunately it still occurs

**Comment by stickz** [comment]
> > Hi @hassonipulus , I would strongly recommend upgrading to [v4.0-beta.2](https://github.com/Novik/ruTorrent/releases/tag/v4.0-beta.2).
> > Please let me know if this resolves your problem. This version is more stable and bug free.
> 
> Unfortunately it still occurs

Did you clear your web browser cache after upgrading? And refresh the page? Have you tried an alternate theme?

**Comment by hassonipulus** [comment]
Yes, only reverting to 3.10 worked

-------- Original Message --------

**Comment by stickz** [comment]
> Yes, only reverting to 3.10 worked

Okay, I believe the problem is the problem is the swizzin install script. I will spin up a cloud server right now and test it.

**Comment by TrimmingFool** [comment]
@hassonipulus I assume you are using [v4.0-beta.2](https://github.com/Novik/ruTorrent/releases/tag/v4.0-beta.2) and not [v4.0-beta.1](https://github.com/Novik/ruTorrent/releases/tag/v4.0-beta.1) since this looks like the theme you are using [club-QuickBox](https://github.com/QuickBox/club-QuickBox) is not updated for [v4.0-beta.2](https://github.com/Novik/ruTorrent/releases/tag/v4.0-beta.2) and thus is broken. The theme maintainer would need to update their theme. I recommend using the MaterialDesign theme.

**Comment by hassonipulus** [comment]
I use the standart theme, still occured

-------- Original Message --------

**Comment by stickz** [comment]
![swizzin_install](https://user-images.githubusercontent.com/9171157/166746110-c9a04fef-a6e0-4e72-8673-e4c5aa096ce4.png)

@hassonipulus This is what I got from using the swizzin on Ubuntu 20.04.4LTS. Is there anything you did differently to setup rTorrent? As you can see my screenshot is different from yours because it's using [v4.0-beta.2](https://github.com/Novik/ruTorrent/releases/tag/v4.0-beta.2)

`bash <(curl -sL git.io/swizzin) && . ~/.bashrc`
`box install rtorrent` (source 0.9.8)
`box install nginx`
`box install rutorrent`

**Comment by hassonipulus** [comment]
https://i.imgur.com/A55lEAE.png
This is the result for me

**Comment by stickz** [comment]
> https://i.imgur.com/A55lEAE.png This is the result for me

I did some more testing. This is caused by not clearing your web browser cache properly when upgrading. 

I strongly recommend using Google Chrome with the following extension. All you have to do is left click on the button.
https://chrome.google.com/webstore/detail/clear-cache/cppjkneekbjaeellbfkmgnhonkkjfpdn

**Comment by hassonipulus** [comment]
I will try it then, same result on mobile.

-------- Original Message --------
