### ISSUE TITLE
erasedata fails to delete folders

### ISSUE THREAD

**Issue by Antorell** [Novik/ruTorrent#2376]
### Please complete the following tasks.

- [X] Web browser cache cleared
- [X] Link provided to install script if applicable
- [X] Web browser, ruTorrent, PHP and OS version provided

### Tell us about your environment

Firefox
4.0
8.1 (Nginx)
Linux Ubuntu 22.04

### Tell us how you installed ruTorrent

git clone https://github.com/Novik/ruTorrent.git

### Describe the bug

The erasedata plugin randomly fails to delete the folder of a downloaded torrent. It happens randomly, and I can't figure out what causes it. 

### Steps to reproduce

Download a torrent or several torrents that have files inside folders, 

When the torrents have finished downloading and seeding, delete using the remove and -> delete data

### Expected behavior

Delete files as well as the folders created by torrents. 

### Additional context

The torrent had finished downloading and seeding like an hour before I delete the files. 

I remember having a similar issue with 3.10 and removing the "> /dev/null 2>&1 &" from the fin.sh (if I remember well) that was added sometimes in 2019 (dade68205ffca2be874e298145a27f00bedc6b82) fixed the issue. I did not remove "> /dev/null 2>&1 &" from the fin.sh in my Rutorrent 4.0 setup.

here an extract of the log
[2022-08-16 23:49:14] erasedata: *** Parse item /var/www/html/ruTorrent/share/users/someuser/settings/erasedata/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA.list
[2022-08-16 23:49:14] erasedata: Successfully delete file /home/someuser/torrents/FOLDER CREATED BY TORRENT/FILE CREATED BY TORRENT.mkv
[2022-08-16 23:49:14] erasedata: Successfully delete file /home/someuser/torrents/FOLDER CREATED BY TORRENT/ OTHER FILE CREATED BY TORRENT.txt
[2022-08-16 23:49:14] erasedata: FAIL Delete file /home/someuser/torrents/FOLDER CREATED BY TORRENT
[2022-08-16 23:49:14] erasedata: FAIL Delete file 1
[2022-08-16 23:49:14] erasedata: FAIL Delete file 1
[2022-08-16 23:49:14] erasedata: Successfully delete file 

edit: removed some folder names I forgot when I sanitized the log output. 

EDIT2: apparently I messed up and linked the wrong commit the commit that caused the issue is (dade68205ffca2be874e298145a27f00bedc6b82)

**Comment by wb6vpm** [comment]
Just a thought, but were there any files extracted after download into folders (such as by the unpack plugin)? If so, that might be why they aren't being deleted, because it's likely using the file information from the torrent to delete the relevant files, and since the extracted files aren't part of it, it wouldn't know about them, or be able to delete them.

**Comment by Antorell** [comment]
Nope. There's nothing to extract, I only download videos anyways. It's a plain rutorrent/rtorrent install with bare minimum plugins. Mediainfo and unpack aren't even loaded. I removed "> /dev/null 2>&1 &" from fin.sh and the issue hasn't happened since I posted the bug report.

**Comment by wb6vpm** [comment]
Glad to hear that in general it isn't still happening at least. For the record, your bug report didn't say any of that, in fact, it says the exact opposite that you DIDN'T remove the "> /dev/null 2>&1 &" from fin.sh (though in context of your update I realize that you did remove it as part of your troubleshooting), and nothing specific about the directories being empty. It just says that some files get deleted and the folder fails to get deleted (which would easily lend to the belief that there was a file left in the folder, given Linux's predisposition to not do it unless -force flag is set, and even then, sometimes still gets cranky, haha)

I only asked the simple question because sometimes we don't think of the simple things that might be happening, so while it seems obvious, when you've been staring at a problem for a while, the obvious isn't always so obvious and gets overlooked, hence why it's common to get a fresh set of eyes on a problem if your stuck.

With it being random, I wonder if it's actually a system problem (not saying specifically a problem with YOUR system, using system as a general statement) vs a ruTorrent issue, where maybe the filesystem database hasn't fully updated yet for whatever reason, therefore the OS thinks there is still a file inside the folder when it gets the command to delete the directory?

Anyways, hopefully you and Novik can figure it out (whether it's just removing that code from fin.sh, or whatever it happens to be) and get the code fixed so that it doesn't happen anymore to you or anyone else.

**Comment by Antorell** [comment]
I only mentioned that I used to have a similar issue with an older version of rutorrent, and removing the  "> /dev/null 2>&1 &" fixed the issue.  Then I emphasized on the fact that I did not remove this line from fin.sh  when I posted the bug report. I didn't say the complete opposite. It's not even in the bug report, it's in the "Additional context".

> With it being random, I wonder if it's actually a system problem (not saying specifically a problem with YOUR system, using system as a general statement) vs a ruTorrent issue, where maybe the filesystem database hasn't fully updated yet for whatever reason, therefore the OS thinks there is still a file inside the folder when it gets the command to delete the directory?

I've had this issue happen randomly on 4 different seedboxes, 3 Debian and 1 Ubuntu using lighthttpd/nginx and different versions of php set as mentioned in the rutorrent wiki. I only reported because I got fed up of seeing this /dev/null stderr/stdout redirect causing this random issue since it was introduced in the commit I mentioned earlier. 

It's a bug report, not a cry for help.

**Comment by stickz** [comment]
This problem is with `rTorrent`. The solution I will accept is for `ruTorrent` to issue the `rm` linux command with the _task plugin, after verifying the torrent has been removed. I'm pinning this issue because it's annoying.

**Comment by Antorell** [comment]
rtorrent and rutorrent are on the same server. I see rtorrent spawn threads to load the erase data plugin, I just don't get why it now needs an "> /dev/null 2>&1 &" stdout that outputs the pid of the thread, and also need a second action to display a "Done" msg when without it rtorrent/rutorrent doesn't randomly leaves any empty folder. I've been running rutorrent without the "> /dev/null 2>&1 &" since my initial post and I haven't and empty folder left over since. 

Here is the output of the command with the /dev/null stdout 
```
bob@Ubuntu:~/bob# mv -f gg.tmp oo.list > /dev/null 2>&1 &
[1] 39848
bob@Ubuntu:~/bob#
[1]+  Done                    mv -f gg.tmp oo.list > /dev/null 2>&1
bob@Ubuntu:~/bob#

```

and without

```
root@Ubuntu:~/bob# mv -f gg.tmp oo.list
root@Ubuntu:~/bob#
root@Ubuntu:~/bob#
```

**Comment by stickz** [comment]
@Antorell Thanks for the added details. Please give this commit a try. It should resolve the problem. https://github.com/Novik/ruTorrent/commit/2f59732ead6b086d849b2addb972f43c48b30d71

**Comment by stickz** [comment]
Resolved in https://github.com/Novik/ruTorrent/commit/2f59732ead6b086d849b2addb972f43c48b30d71 . Please comment here if there is any further issues.
