### ISSUE TITLE
Ratio Groups - Ability to set UL,GiB to 0 (Remove 0.01GiB Hard limit)

### ISSUE THREAD

**Issue by xxtensazenxx** [Novik/ruTorrent#2377]
### Is your feature request related to a problem?

I am unable to set the UL,GiB to 0 anymore. The hard limit is 10MiB.

### Describe the solution you'd like

In The Ratio Groups options,  I would like the option to set the min to 0mb again. I had this set up previously and it worked fine. There is now a hard limit at 0.01 and when set to 0 it reverts back to the hard limit.

### Additional context

This is useful with exratio and wanting to stop torrent's immediately after download. I seed most but I have a few trackers I don't want to seed to.

**Comment by stickz** [comment]
Hi @xxtensazenxx, this limit was created with PR #2266. The upload ratio was changed from MiB to GiB. It is no longer possible to allow a value less than 0.01, since the unit of measurement was changed from a whole number to a decimal number.

However, cec7fca056d753c9724a5d20843d31ee50e4aa56 now allows the value "0" to stop torrents immediately. Please test this change, to verify it works as intended!
