### ISSUE TITLE
RSS filters not updating

### ISSUE THREAD

**Issue by fredentoft** [Novik/ruTorrent#2381]
### Please complete the following tasks.

- [X] Web browser cache cleared
- [X] Link provided to install script if applicable
- [X] Web browser, ruTorrent, PHP and OS version provided

### Tell us about your environment

Web Browser: Firefox 104, Chrome 103 + others including incognito mode
ruTorrent: 3.8
PHP: 8.1.2
OS: Ubuntu  22.04.1 LTS

### Tell us how you installed ruTorrent

Unzipped and manually copied files into webserver file structure.
Copied files of the plugins previsously used in earlier version of rutorrent.
Copied userspecific settings 'share/users/{username}' folder from previous version.
Manually transferred applicable settings from previous version (not sure which files right now)

### Describe the bug

Suddenly unable to update RSS filters, only receive:
Bad response from server: (500 [error,setfilters])

### Steps to reproduce

1. Click "RSS Downloader" icon
2. Make any change (add/remove any character from any filter for example)
3. click OK
4. Instead of updating filters there is a message in log tab: "Bad response from server: (500 [error,setfilters])"

### Expected behavior

Expected filters to be updated.

**Comment by fredentoft** [comment]
Tried upping php logging to debug, but could not see any relevant data in logs

**Comment by fredentoft** [comment]
Same error after removing the filters file altogether, just trying to add one test filter:

Form data from DevTools (firefox):
`mode=setfilters&name=New%20filter&pattern=%2Ftest%2Fi&enabled=1&chktitle=1&chklink=0&chkdesc=0&exclude=&hash=&start=1&addPath=1&dir=&label=testlabel&interval=72&no=1&ratio=`

`mode | "setfilters"
-- | --
name | "New filter"
pattern | "/test/i"
enabled | "1"
chktitle | "1"
chklink | "0"
chkdesc | "0"
exclude | ""
hash | ""
start | "1"
addPath | "1"
dir | ""
label | "testlabel"
interval | "72"
no | "1"
ratio | ""
`

Will try a full upgrade to Master when possible

**Comment by fredentoft** [comment]
Editing feeds themselves works, updating feeds into their respective cache files work.
File ownerships and permissions are identical between files.

addgroup gives same 500 error
`mode | "addgroup"
-- | --
label | "Testgrp"
hash | ""
rss | "7d9dbabc3891b00e31cd69a031c5e60b"`

**Comment by fredentoft** [comment]
Found some output in nginx error log:
`FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function create_function() in /srv/www/htdocs/rutorrent/plugins/rss/rss.php:645
Stack trace:
#0 /srv/www/htdocs/rutorrent/plugins/rss/rss.php(919): rRSSFilterList->sort()
#1 /srv/www/htdocs/rutorrent/plugins/rss/action.php(263): rRSSManager->setFilters()
#2 {main}
  thrown in /srv/www/htdocs/rutorrent/plugins/rss/rss.php on line 645" while reading response header from upstream, client: [127.0.0.1](http://127.0.0.1/)`

**Comment by fredentoft** [comment]
Apparently create_function was deprecated in php 7.2

**Comment by fredentoft** [comment]
Looking at code in Master the call to the removed function has been fixed.
I will upgrade.

**Comment by stickz** [comment]
Hi @fredentoft, I would strongly recommend updating your ruTorrent version to master [55e533a](https://github.com/Novik/ruTorrent/archive/55e533ae4b7841fe10beaec04048d3ada698075f.zip). You need version 4 because you're running PHP 8. There are some important bug fixes in this branch and it is very stable right now.  The only major change since last pre-release is with the RSS plugin. If there are any issues with the RSS plugin, you can disable it and file an issue report.

If you choose to update to version 4, it is NOT backwards compatible with version 3. Backup everything then copy and replace all the folders into your web server file structure. Afterwards, clear your web browser cache and refresh the page. Lastly, disable any old problematic plugins and find the latest version on a 3rd party GitHub repository. See [discussions](https://github.com/Novik/ruTorrent/discussions) for questions & plugin ports.
