### ISSUE TITLE
Incorrect Cache-Control in the primitive CachedEcho::send

### ISSUE THREAD

**Issue by Novik** [Novik/ruTorrent#2499]
### Please complete the following tasks.

- [X] Web browser cache cleared
- [X] Link provided to install script if applicable
- [X] Web browser, ruTorrent, PHP and OS version provided

### Tell us about your environment

N/A

### Tell us how you installed ruTorrent

N/A

### Describe the bug

Now we have 'Cache-Control: max-age' in the primitive CachedEcho::send. 
This feature break interface at all places, where it used.
https://github.com/Novik/ruTorrent/blob/0d44ec95f5093104671313dc5fb37ccfff5d345f/plugins/rssurlrewrite/action.php#L30
https://github.com/Novik/ruTorrent/blob/0d44ec95f5093104671313dc5fb37ccfff5d345f/plugins/extratio/action.php#L47
and other places.

Example: 
User add new rule in the rssurlrewrite plugin, close dialog, reopen dialog... and he can't see his rule.
BTW you can't reproduce this case with an open browser inspector with 'Disable cache' option.

Also check tis commit - 
https://github.com/Novik/ruTorrent/commit/3722b0a1f8a46f321a1c7aaa30d186f3bd1e3780
You should not turn off caching. Yuo should remove Cache-Control. Now we do not have any place, where this feature may be useful.

**Comment by stickz** [comment]
I'm on a mobile device currently with limited access to code. The main reason `max-age` was added is to mitigate caching issues in `getplugins.php`. A very large user base was filing bug reports about caching issues during version upgrades. Linux maintainers were also dissatisfied about this during package upgrades. 

If the feature is not useful for `action.php`, perhaps it should only be used in `getplugins.php`. I strongly believe we should apply this change in `v4.2` and disable `action.php` caching for `v4.1`. What do you think?

The plan is to make version `v4.1` very stable and support it for a long time. Platforms are working on upgrading from version 3 to 4 right now. Any major change could setback the goal of rolling out `v4.1` to Linux and other important platforms. We need to provide them with a release that is extremely stable at all costs. And continue to support it with only important bug fixes.

**Comment by Novik** [comment]
> If the feature is not useful for action.php, perhaps it should only be used in getplugins.php

This feature is not userful in any place. Case:
1) Set ```$cachedPluginLoading = true;``` in the config
2) Load ruTorrent interface
3) Unload several plugins from the ```Plugins``` tab
4) Reload ruTorrent interface, check these plugins and... they are loaded!
5) Set ```$cachedPluginLoading = false;``` in the config
6) Reload ruTorrent interface, check these plugins and... they are loaded again! And this will continue during 3 hours after config changes.

And this case is not standalone. For example, check this - https://github.com/Novik/ruTorrent/blob/master/plugins/history/init.php#L9
This plugin uses initialization for transmit his dynamic options to the frontend. I.e. with this feature you may change something in the options dialog for plugin ```unpack```, reload interface, and you will not see your changes...

I.e. this feature is a reason for user's issues and unpredictable errors.

> I strongly believe we should apply this change in v4.2 and disable action.php caching for v4.1. What do you think?

I think we should remove this bugged feature.

**Comment by stickz** [comment]
> I think we should remove this bugged feature.

Okay, I will remove the bugged feature tomorrow from `v4.1`. I think we should keep caching disabled by default for plugins. Users can turn on the setting if required. 

I can work on a fix in `v4.2` to bust the plugin cache from the web browser. We can send a PHP request parameter with the version number.

**Comment by TrimmingFool** [comment]
> At the point where Cached::send is called, most of the processing/loading is already done. I tested that returning 304 Not Modified at that point does not provide a speedup.
If we assume that users do not update the plugin sources (and expect the changes to show up without disabling the cache), we could try exiting getplugins.php early with 304 Not Modified by deriving the etag from a version number. However, loading all php plugins by calling require_once (or by simply not exiting early) should not be forgotten.  https://github.com/Novik/ruTorrent/pull/2469#issuecomment-1492702690)

If composing of js code of the plugins is really the performance bottleneck, I suggest parallelizing this. 

1. Instead of the js, `getplugins.php` could answer with ordered `(name, version)` tuples where `init.js` is available
2. Then, the browser could add `<script src="php/getpluginjs.php?name={name}&version={vers}" type="text/javascript"></script>` in the given order.

The browser is then able to rely on its cache as long as `name` and `version` remain the same.

3. Additionally, if `require_once` is (also) taking too long `getplugins.php` could alternatively answer with `(name, version, js_available, php_available)` tuples
4. Then, the browser could POST `name`s to `loadplugins.php` (which calls `require_once`) where `php_available` (while loading the javascript as in 2.)
However, this might require some additional error handling in case `loadpluings.php` fails (due to a faulty plugin, for instance).

@Novik I don't think that manually saving `${hash}.composed.js` is a good idea.

**Comment by Novik** [comment]
> Instead of the js, getplugins.php could answer with ordered (name, version) tuples where init.js is available

And how you will calculate this version for the each plugin? Developer must manually touch it on the every changes?

> I don't think that manually saving ${hash}.composed.js is a good idea.

Why? This give us performance burst in any case - have browser corresponding cache or not.

**Comment by stickz** [comment]
We can send the version from `webui.js` to `getplugins.php?version={version}`. Then we replace the following line here:
https://github.com/Novik/ruTorrent/blob/48933089370b667e8d3b19fb8f9b92bc6db5409d/php/getplugins.php#L526

Instead of using `CachedEcho::send` and `file_get_contents`, we use jQuery to inject the JavaScript into the header.
```
$script="<script type=\"text/javascript\ src=\"".$plugin["js"]."?v=".$version."\"></script>"
$('head').append($script);
```
Final string would look something like this: 
`<script type="text/javascript" src="./plugins/autotools/init.js?v=415"></script>`

When we upgrade versions, there would be no more caching issues. Plugins would be permanently cached for each version.

**Comment by TrimmingFool** [comment]
> `<script type="text/javascript" src="./plugins/autotools/init.js?v=415"></script>`

Yes, although I suggest using the plugin version (from the `plugin.info`) instead.

https://github.com/Novik/ruTorrent/blob/48933089370b667e8d3b19fb8f9b92bc6db5409d/php/getplugins.php#L518
> And how you will calculate this version for the each plugin? Developer must manually touch it on the every changes?

Currently, plugins only have a 4.1 version. If a plugin is changed, the 'patch' version could be incremented only for direct changes to the plugin: `4.1.0` -> `4.1.1`.

> And how you will calculate this version for the each plugin? Developer must manually touch it on the every changes?

Developers can temporarily deactivate the browser's cache to see js modifications.

**Comment by TrimmingFool** [comment]
Caching of the JS code ( as I suggested ) does not really work. At least not without some changes to how plugins initialize themselves. I did not know that some plugins use `init.php` to prepend JavaScript before `init.js`. For instance, geoip communicates its options this way:  https://github.com/Novik/ruTorrent/blob/96cd4bb2cbbb2b8035996a78f774e12c1a8aafd7/plugins/geoip/init.php#L14
