### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'getPlaceholder')

### ISSUE THREAD

**Issue by koblack** [Novik/ruTorrent#2593]
### Please complete the following tasks.

- [X] Web browser cache cleared
- [X] Copied everything if upgrading to v4.0 or master
- [X] Web browser and ruTorrent version provided

### Tell us about your environment

Web Browser: Google Chrome 119.0.6045.124
ruTorrent branch v4.2: https://github.com/Novik/ruTorrent/commit/90fe06c64671e8d993c5300ccd4751ece2d40b9d
PHP: PHP 7.4.3
OS: Ubuntu 20.04.6 LTS
web server: lighttpd/1.4.55

### What were you trying to do?

1. press f6 (hide details)
2. press f5 (refresh)
3. press f6 (show details)
4. error

### What us the error message?

Uncaught TypeError: Cannot read properties of undefined (reading 'getPlaceholder')

### Give us the stack trace.

webui.js?v=427:3186 Uncaught TypeError: Cannot read properties of undefined (reading 'getPlaceholder') from TypeError: Cannot read properties of undefined (reading 'getPlaceholder')
    at rTraficGraph.resize (<anonymous>:7264:25)
    at theWebUI.resizeBottom (<anonymous>:7296:20)
    at Object.resize (http://box/ruTorrent/js/webui.js?v=427:2873:13)
    at Object.toggleDetails (http://box/ruTorrent/js/webui.js?v=427:2918:18)
    at HTMLDocument.keyEvent (http://box/ruTorrent/js/webui.js?v=427:324:16)
    at HTMLDocument.dispatch (http://box/ruTorrent/js/jquery.js?v=427:2:39997)
    at v.handle (http://box/ruTorrent/js/jquery.js?v=427:2:37968)

**Comment by stickz** [comment]
Did you clear your web browser cache when installing the latest v4.2 branch commit? There is no cache buster when installing commits. It's highly possible for an error of this type to be caused by a stale cache. This error in particular is pointing here.
https://github.com/Novik/ruTorrent/blob/90fe06c64671e8d993c5300ccd4751ece2d40b9d/js/webui.js#L3186

As you can see this is the physical line that prints the stack trace to your web browser console. We have a null check in place here, however for `window.onerror` the `Error` object should not be undefined. 

Even if this is a caching issue, we still need to resolve it. We just need to know which type of error to understand the problem.

**Comment by koblack** [comment]
The cache has been cleared few times.
I also checked using the browser in private mode.

**Comment by stickz** [comment]
> The cache has been cleared few times. I also checked using the browser in private mode.

Could you try https://github.com/Novik/ruTorrent/commit/c9ea93b33e30b44da773826c99b82243b4e043a7 ? I will release anther hotfix if this resolves the problem. Since, we have 3 important bug fixes.

**Comment by koblack** [comment]
Thank you very much.
Checked, everything works as it should.
