### ISSUE TITLE
Limited context menu improvements on mobile

### ISSUE THREAD

**Issue by stickz** [Novik/ruTorrent#2734]
### What would you like changed about the web client?

I would like the expandable context menu for mobile to be improved for the next release.

### Describe the solution you'd like and propose possible alternatives.

1. I would recommend placing `Start`, `Pause` and `Stop` on the same line on mobile (if feasible) to create extra room.
2. I would recommend dropping the `Plugins...` main context on mobile. Then bring the sub contexts to main context on mobile using the Plugins icon. (It should also support custom plugins as required)
    - `URL Replacement in RSS`
    - `Ratio Rules`
    - `Bulk Loading`

### Provide information and resources about the environment hosting the web client.

**Server:** ruTorrent v5.0-Stable on Ubuntu 24.04 LTS
**Web Client:** Google Chrome 129.0.6668.59
**Installation Method:** zip source from version release

### Additional context

![ruTorrent_context_menu_improvements](https://github.com/user-attachments/assets/420a1f66-48d1-4034-b9bc-0792df4b35cf)

**Comment by stickz** [comment]
@jevenski What are your thoughts on this suggested improvement for the next release?

**Comment by jevenski** [comment]
Yes, we can definitely bring the three brothers and sisters (Start, Pause, Stop) onto one line. There is plenty of room horizontally for them. 

As for the Plugins submenu, I was thinking about adopting Bootstrap's [dropdowns](https://getbootstrap.com/docs/5.3/components/dropdowns/) to fit the navbar. The old dropdown menu on the navbar shares the same mechanism with the context menu in the torrent list, the file list, etc. I think this is inefficient because the submenu items are static on the navbar, while the menu items on the context menus are dynamic, depending on what users are right-clicking on. Look at the init check for the `theContextMenu` object at Line 302 - Line 307: that looks like an if-else nightmare. 
https://github.com/Novik/ruTorrent/blob/b125b6901d23085c784c7fb9d4a3c1e8b55e62c7/js/objects.js#L302-L307
So for the navbar sub-menus, we can add the sub-menu items directly to the DOM, and make the containing icon a dropdown item. The same goes for the search button on the navbar.

**Comment by stickz** [comment]
Okay sounds good @jevenski! Let's going with the plan of Bootstraps dropdowns!
