### ISSUE TITLE
Can we get Commit 198ea6c merged

### ISSUE THREAD

**Issue by quadcom** [Novik/ruTorrent#2789]
### Please complete the following tasks.

- [X] Web browser cache cleared
- [X] Link provided to install script if applicable
- [X] Not using broken rtinst install script
- [X] Web browser, ruTorrent, PHP and OS version provided

### Tell us about your environment

FF/Ch
ExtRatio v 5.1 (as shown in the plugins list)

Can we get Commit 198ea6c reviewed and merged?

ExtRatio is broken, a least on my server and it appears that someone has already identified the problem and provided a fix on Oct 10th.

https://github.com/Novik/ruTorrent/commit/198ea6c074a521e20de9fc61e933c34a9fff107a

I could not find any ticket regarding this problem yet.

https://youtu.be/YqZyCBziI2I

### Tell us how you installed ruTorrent

Seedbox provider

### Describe the bug

ExtRatio is not applying the config created in the UI.

### Steps to reproduce

Clear your Ratio Rules list
reiew the blank ratiorules.dat file.
Add a rule via the UI.
Compare the default ratiorules.dat with the new version that has the new rule.
The new rule in the ratiorules.dat file will not match the config entered in the UI.
The default mininova.org match is saved in the dat.

**Comment by stickz** [comment]
Thanks for the youtube video @quadcom ! Whatbox is running a stable - bleeding edge configuration of ruTorrent. v5.1 beta 4. Therefore, the mentioned commit is already installed on your server. Merged as part of #2725.

ExtRatio is a new bleeding edge plugin, that was not previously possible to enable on Whatbox due to upstream limits. We removed this limitation in v5.1. We will investigate and resolve any associated problems with this new feature!

Please let us know if Beta 5 resolves this problem, once it gets deployed to Whatbox. We have 1 more issue to resolve, then we'll be tagging a newer release control version for @anthonyryan1 at Whatbox to deploy.

**Comment by quadcom** [comment]
@stickz  my issue was resolved with your fix. This issue may not be related after all.
