### ISSUE TITLE
Feature Request: bottom line info

### ISSUE THREAD

**Issue by nicobubulle** [Novik/ruTorrent#354]
_From [zilvinas...@gmail.com](https://code.google.com/u/112358859614546941183/) on March 21, 2010 08:41:22_

rtorrent has a bottom line in GUI shows current info about a lot of things. http://libtorrent.rakshasa.no/wiki/RTorrentUserGuide#BottomlineinGUIshowscurrentinfoaboutalotofthings .

Would be great if rutorrent would include the following info along with
currently available Upload and Download Speeds.

-download slots (current/max)
-HTTP requests (current/max)
-upload slots (current/max)
-handshakes/open sockets/max open sockets
-open files/max open files

I would also suggest moving rTorrent version info out from bottom line to
"Help -> About" (Ctrl+F1) which is the most common way of showing version
numbers.

_Original issue: http://code.google.com/p/rutorrent/issues/detail?id=356_

**Comment by scoobynz** [comment]
Is this still valid? i.e. that rtorrent's bottom line cannot be displayed in rutorrent due to xmlrpc limitations?

I find bottom line of rtorrent very useful in checking if your configuration is correct, i.e. that you have the correct number of slots, connections etc available. It allows you to monitor issues with your config essentially.

**Comment by Novik** [comment]
This is still valid, sorry. But you are free for implementing corresponding features (drag-n-drop etc) inside your own plugin.
