### ISSUE TITLE
Can't add torrent file.

### ISSUE THREAD

**Issue by igribkov** [Novik/ruTorrent#966]
Please could you investigate this problem. Some torrent files are not added to rTorrent through web interface. For example try to add this one http://hdclub.org/details.php?id=13048
http://rghost.ru/58969626

**Comment by eceforge** [comment]
Old thread - I know, but just in case anyone runs into the same issue: 

I ran across this issue while trying to download an offline version of wikipedia with a .torrent files size of 1.5MB, I too thought it was not working because of the php.ini upload_max_filesize limit --  I increased it from the default of 2M (which should have already been large enough) to 4M with no change (no surprise).

A look at journalctrl -f while attempting to add the file from the web interface showed that nginx was actually the one that was rejecting the upload. Adding the "client_max_body_size" option to the server section in the nginx.conf file and setting the option to something high (I set to 20M) fixes this issue.
